CREATE TABLE `PI_INSTANCE`(
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(200),
	`LAST_REGISTERED_ADDRESS` VARCHAR(200),
	PRIMARY KEY(`ID`)
);

ALTER TABLE `PIN` ADD `PI_INSTANCE_ID` BIGINT NOT NULL;
ALTER TABLE `PIN` ADD `IS_AVAILABLE` BIT;

ALTER TABLE `PIN` 
ADD CONSTRAINT `FK_PIN_PI_INSTANCE_ID` FOREIGN KEY (PI_INSTANCE_ID)
REFERENCES `PI_INSTANCE` (ID);

