CREATE TABLE `UI_BUTTON`(
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(200),
	`ICON_ID` BIGINT,
	`TYPE_ID` BIGINT,
	`LINKED_TO_PIN_ID` BIGINT,
	`LINKED_TO_PIN_GROUP_ID` BIGINT,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `UI_BUTTON_TYPE`(
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(200),
	PRIMARY KEY(`ID`)
);

CREATE TABLE `ICON`(
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(200),
	`CONTENT` LONGTEXT,
	PRIMARY KEY(ID)
);

ALTER TABLE `UI_BUTTON` 
ADD CONSTRAINT `FK_UI_BUTTON_ICON_ID` FOREIGN KEY (ICON_ID)
REFERENCES `ICON` (ID);

ALTER TABLE `UI_BUTTON` 
ADD CONSTRAINT `FK_UI_BUTTON_TYPE_ID` FOREIGN KEY (TYPE_ID)
REFERENCES `UI_BUTTON_TYPE` (ID);

ALTER TABLE `UI_BUTTON` 
ADD CONSTRAINT `FK_UI_BUTTON_LINKED_TO_PIN_ID` FOREIGN KEY (LINKED_TO_PIN_ID)
REFERENCES `PIN` (ID);

ALTER TABLE `UI_BUTTON` 
ADD CONSTRAINT `FK_UI_BUTTON_LINKED_TO_PIN_GROUP_ID` FOREIGN KEY (LINKED_TO_PIN_GROUP_ID)
REFERENCES `PIN_GROUP` (ID);


