
CREATE TABLE UI_BUTTONS_PANEL ( ID BIGINT NOT NULL AUTO_INCREMENT, NAME VARCHAR(200), PRIMARY KEY (ID) );

INSERT INTO UI_BUTTONS_PANEL(ID, NAME) VALUES(1, 'Main panel');

ALTER TABLE UI_BUTTON ADD BUTTONS_PANEL_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE UI_BUTTON ADD CONSTRAINT FK_UIB_BUTTONS_PANEL_ID FOREIGN KEY (BUTTONS_PANEL_ID) REFERENCES UI_BUTTONS_PANEL(ID);