CREATE TABLE PIN_CALENDAR_ACTION(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200),
PRIMARY KEY(ID));

INSERT INTO pin_calendar_action(id, name) VALUES(1, 'ON');
INSERT INTO pin_calendar_action(id, name) VALUES(2, 'OFF');
INSERT INTO pin_calendar_action(id, name) VALUES(4, 'ON -> OFF');
INSERT INTO pin_calendar_action(id, name) VALUES(5, 'OFF -> ON');

CREATE TABLE PIN_CALENDAR(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(200),
	PIN_ID BIGINT NOT NULL,
	DAY INT,
	MONTH INT,
	YEAR INT,
	HOUR INT,
	MINUTE INT,
	ACTION_ID BIGINT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY (PIN_ID) REFERENCES PIN(ID),
	FOREIGN KEY (ACTION_ID) REFERENCES PIN_CALENDAR_ACTION(ID)
);

